export const MAX_DEPTH = 6
export const ROOT_LABEL = 'entity'
export const ROOT_ID = 'Q35120'

export { Arrow } from './Arrow'
export { ArrowData } from './ArrowData'
export { Circle } from './Circle'
export { ComboboxItem } from './ComboboxItem'
export { Label } from './Label'
export { Link } from './Link'
export { MappingData } from './MappingData'
export { MappingNode } from './MappingNode'
export { Node } from './Node'
export { PathNode } from './PathNode'
export { Position } from './Position'
